package com.unum.keyboard.text

import com.unum.keyboard.core.TextAction
import kotlin.math.abs
import kotlin.math.roundToInt

/**
 * Controls cursor movement via the spacebar trackpad gesture.
 *
 * When the user long-presses the spacebar and drags, the cursor moves
 * proportionally to the horizontal drag distance. Vertical drag can
 * optionally control text selection.
 *
 * Inspired by iPhone's 3D Touch trackpad and BlackBerry's trackpad nav.
 */
class CursorController(
    /** Horizontal pixels per cursor position (lower = more sensitive) */
    val sensitivity: Float = DEFAULT_SENSITIVITY,
    /** Long-press duration in ms before trackpad activates */
    val activationDelay: Long = DEFAULT_ACTIVATION_DELAY,
    /** Enable vertical drag for text selection */
    val verticalSelectionEnabled: Boolean = true
) {
    /** Whether trackpad mode is currently active */
    var isActive: Boolean = false
        private set

    /** Whether we're in selection mode (vertical drag detected) */
    var isSelecting: Boolean = false
        private set

    private var startX: Float = 0f
    private var startY: Float = 0f
    private var startTime: Long = 0L
    private var lastCursorOffset: Int = 0
    private var lastSelectionOffset: Int = 0
    private var accumulatedX: Float = 0f
    private var accumulatedY: Float = 0f

    /** Pending text actions generated by trackpad movement */
    private val _pendingActions = mutableListOf<TextAction>()

    /**
     * Called when touch begins on the spacebar.
     */
    fun onTouchStart(x: Float, y: Float, timestamp: Long) {
        startX = x
        startY = y
        startTime = timestamp
        lastCursorOffset = 0
        lastSelectionOffset = 0
        accumulatedX = 0f
        accumulatedY = 0f
        isActive = false
        isSelecting = false
        _pendingActions.clear()
    }

    /**
     * Called during touch move on the spacebar.
     * Returns true if trackpad mode consumed this event.
     */
    fun onTouchMove(x: Float, y: Float, timestamp: Long): Boolean {
        val elapsed = timestamp - startTime

        // Check if we've held long enough to activate trackpad
        if (!isActive) {
            if (elapsed >= activationDelay) {
                isActive = true
                // Reset accumulation from activation point
                startX = x
                startY = y
                accumulatedX = 0f
                accumulatedY = 0f
            } else {
                return false
            }
        }

        val dx = x - startX
        val dy = y - startY

        accumulatedX = dx
        accumulatedY = dy

        // Check for vertical drag → selection mode
        if (verticalSelectionEnabled && abs(dy) > SELECTION_THRESHOLD && !isSelecting) {
            isSelecting = true
        }

        // Calculate cursor offset from horizontal movement
        val cursorOffset = (dx / sensitivity).roundToInt()
        val deltaOffset = cursorOffset - lastCursorOffset

        if (deltaOffset != 0) {
            if (isSelecting) {
                _pendingActions.add(TextAction.ExtendSelection(deltaOffset))
                lastSelectionOffset += deltaOffset
            } else {
                _pendingActions.add(TextAction.MoveCursor(deltaOffset))
            }
            lastCursorOffset = cursorOffset
        }

        return true
    }

    /**
     * Called when touch ends on the spacebar.
     * Returns true if trackpad mode was active (meaning the touch
     * should NOT be treated as a space key press).
     */
    fun onTouchEnd(x: Float, y: Float, timestamp: Long): Boolean {
        val wasActive = isActive
        isActive = false
        isSelecting = false
        return wasActive
    }

    /**
     * Cancel trackpad mode.
     */
    fun cancel() {
        isActive = false
        isSelecting = false
        _pendingActions.clear()
    }

    /**
     * Drain all pending text actions.
     * Returns actions and clears the internal queue.
     */
    fun drainActions(): List<TextAction> {
        val actions = _pendingActions.toList()
        _pendingActions.clear()
        return actions
    }

    /**
     * Get the total cursor displacement since activation.
     */
    val totalCursorOffset: Int get() = lastCursorOffset

    companion object {
        /** Default pixels per cursor position */
        const val DEFAULT_SENSITIVITY = 15f
        /** Default long-press delay before activation (ms) */
        const val DEFAULT_ACTIVATION_DELAY = 300L
        /** Vertical pixel threshold to enter selection mode */
        const val SELECTION_THRESHOLD = 30f
    }
}
